### ISSUE TITLE
No enum constant org.holoeasy.util.VersionEnum.CRAFTBUK - Paper

### ISSUE THREAD

**Issue by AerWyn81** [unldenis/holoeasy#57]
Hi! I have a little issue using the lib.

Running:
Paper version 1.20.6-137-master@bd5867a (2024-06-04T21:04:28Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
Holoeasy version: com.github.unldenis.holoeasy:holoeasy-core:3.4.0
ProtcolLib: latest build #723 

Implementation:
```
    public IHologram create(String name, Location location, List<String> lines, int displayRange) {
        HoloLibSingleton.getHologramPool().registerHolograms(() -> hologram(location.subtract(0, 1.3, 0), () -> {
            lines.forEach(HologramBuilder::textline);
        }));

        for (Player pl : Collections.synchronizedCollection(Bukkit.getOnlinePlayers())) {
            hide(pl);
        }

        return this;
    }
```

```
java.lang.ExceptionInInitializerError: null
	at HeadBlocks-2.5.1.jar/org.holoeasy.packet.IPacket$DefaultImpls.isCurrentVersion(IPacket.kt:29) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.packet.delete.IDeletePacket$DefaultImpls.isCurrentVersion(IDeletePacket.kt:6) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.packet.delete.DeletePacketA.isCurrentVersion(DeletePacketA.kt:9) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.packet.PacketType.getCurrImpl(IPacket.kt:41) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.packet.PacketType.access$getCurrImpl(IPacket.kt:39) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.packet.PacketType$DELETE$2.invoke(IPacket.kt:59) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.packet.PacketType$DELETE$2.invoke(IPacket.kt:59) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.packet.PacketType.getDELETE(IPacket.kt:59) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.line.Line.<init>(Line.kt:21) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.line.Line.<init>(Line.kt:14) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.line.TextLine.<init>(TextLine.kt:20) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.builder.Service.textline(Service.kt:54) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.builder.HologramBuilder.textline(HologramBuilder.java:72) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/fr.aerwyn81.headblocks.holograms.types.DefaultHologram.lambda$create$0(DefaultHologram.java:39) ~[HeadBlocks-2.5.1.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at HeadBlocks-2.5.1.jar/fr.aerwyn81.headblocks.holograms.types.DefaultHologram.lambda$create$1(DefaultHologram.java:39) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.builder.HologramBuilder.hologram(HologramBuilder.java:54) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/fr.aerwyn81.headblocks.holograms.types.DefaultHologram.lambda$create$2(DefaultHologram.java:38) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.builder.HologramBuilder.registerHolograms(HologramBuilder.java:25) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.pool.IHologramPool$DefaultImpls.registerHolograms(IHologramPool.kt:20) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.pool.HologramPool.registerHolograms(HologramPool.kt:18) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/fr.aerwyn81.headblocks.holograms.types.DefaultHologram.create(DefaultHologram.java:37) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/fr.aerwyn81.headblocks.holograms.InternalHologram.createHologram(InternalHologram.java:53) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/fr.aerwyn81.headblocks.services.HologramService.internalCreateHologram(HologramService.java:90) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/fr.aerwyn81.headblocks.services.HologramService.createHolograms(HologramService.java:74) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/fr.aerwyn81.headblocks.services.HologramService.load(HologramService.java:57) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/fr.aerwyn81.headblocks.HeadBlocks.onEnable(HeadBlocks.java:95) ~[HeadBlocks-2.5.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant org.holoeasy.util.VersionEnum.CRAFTBUK
	at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
	at org.bukkit.craftbukkit.legacy.FieldRename.valueOf(FieldRename.java:54) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at HeadBlocks-2.5.1.jar/org.holoeasy.util.VersionEnum.BUKKIT_CUSTOM_METHOD_org_bukkit_craftbukkit_legacy_FieldRename_valueOf(VersionUtil.kt) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.util.VersionEnum.valueOf(VersionUtil.kt) ~[HeadBlocks-2.5.1.jar:?]
	at HeadBlocks-2.5.1.jar/org.holoeasy.util.VersionUtil.<clinit>(VersionUtil.kt:33) ~[HeadBlocks-2.5.1.jar:?]
	... 40 more
```

Regards,

**Comment by AerWyn81** [comment]
Found the issue, with Paper change announced the 09/24/2023 on their Discord [here](https://discord.com/channels/289587909051416579/1077385604012179486/1155459001090318346). you should adapt your implementation [here](https://github.com/unldenis/holoeasy/blob/3ff81f326600124621fcfcce4d9124fe24837bdf/holoeasy-core/src/main/kotlin/org/holoeasy/util/VersionUtil.kt#L30). Sorry I'm not familiar to Kotlin, I can't made a PR :/

**Comment by unldenis** [comment]
Merged!
