### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by tgross03** [unldenis/holoeasy#67]
Hey, I am using `holoeasy-core` 4.1.0 via Maven and I am getting the following Exception:

```console
[19:45:02] [Craft Scheduler Thread - 3 - Parcour/WARN]: [Parcour] Plugin Parcour v1.0.0-RELEASE generated an exception while executing task 22
java.lang.NullPointerException: constructor
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
	at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getConstructorAccessor(MethodHandleHelper.java:70) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.accessors.Accessors.getConstructorAccessor(Accessors.java:167) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.accessors.Accessors.getConstructorAccessor(Accessors.java:145) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.LegacyDataWatcher.newHandle(LegacyDataWatcher.java:113) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.LegacyDataWatcher.<init>(LegacyDataWatcher.java:108) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.LegacyDataWatcher.<init>(LegacyDataWatcher.java:85) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.<init>(WrappedDataWatcher.java:86) ~[ProtocolLib.jar:?]
	at org.holoeasy.packet.metadata.text.MetadataTextPacketD.metadata(MetadataTextPacketD.kt:18) ~[parcour-1.0.0-RELEASE.jar:?]
	at org.holoeasy.packet.metadata.text.IMetadataTextPacket$DefaultImpls.metadata$default(IMetadataTextPacket.kt:8) ~[parcour-1.0.0-RELEASE.jar:?]
	at org.holoeasy.line.TextLine$pvt$1.show(TextLine.kt:93) ~[parcour-1.0.0-RELEASE.jar:?]
	at org.holoeasy.hologram.Hologram.show(Hologram.kt:103) ~[parcour-1.0.0-RELEASE.jar:?]
	at org.holoeasy.pool.HologramPool.hologramTick$lambda$4(HologramPool.kt:71) ~[parcour-1.0.0-RELEASE.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-550]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1575) ~[?:?]
[19:45:02] [Craft Scheduler Thread - 1 - Parcour/WARN]: [Parcour] Plugin Parcour v1.0.0-RELEASE generated an exception while executing task 22
java.lang.NullPointerException: constructor
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
	at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getConstructorAccessor(MethodHandleHelper.java:70) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.accessors.Accessors.getConstructorAccessor(Accessors.java:167) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.accessors.Accessors.getConstructorAccessor(Accessors.java:145) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.LegacyDataWatcher.newHandle(LegacyDataWatcher.java:113) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.LegacyDataWatcher.<init>(LegacyDataWatcher.java:108) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.LegacyDataWatcher.<init>(LegacyDataWatcher.java:85) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.<init>(WrappedDataWatcher.java:86) ~[ProtocolLib.jar:?]
	at org.holoeasy.packet.metadata.text.MetadataTextPacketD.metadata(MetadataTextPacketD.kt:18) ~[parcour-1.0.0-RELEASE.jar:?]
	at org.holoeasy.packet.metadata.text.IMetadataTextPacket$DefaultImpls.metadata$default(IMetadataTextPacket.kt:8) ~[parcour-1.0.0-RELEASE.jar:?]
	at org.holoeasy.line.TextLine$pvt$1.show(TextLine.kt:93) ~[parcour-1.0.0-RELEASE.jar:?]
	at org.holoeasy.hologram.Hologram.show(Hologram.kt:103) ~[parcour-1.0.0-RELEASE.jar:?]
	at org.holoeasy.pool.HologramPool.hologramTick$lambda$4(HologramPool.kt:71) ~[parcour-1.0.0-RELEASE.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-550]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

I am using [ProtocolLib 5.3.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/5.3.0) on a Paper 1.19.4 server. The class I use to inherit from `Hologram` is the following:

```java
    public static class CheckpointHologram extends Hologram {

        ITextLine firstLine = null;
        ITextLine secondLine = null;
        ITextLine thirdLine = null;


        public CheckpointHologram(@NotNull Location location, Course course, Checkpoint checkpoint) {
            super(location);

            switch (checkpoint.getType()) {
                case START -> {
                    firstLine = textLine("§b§l> START <");
                    secondLine = textLine("§7Parkour: §e{}", new TextLineModifiers().args(course.getName()));
                    thirdLine = textLine("§7Schwierigkeit: {}",
                            new TextLineModifiers().args(Parcour.getColoredText(course.getDifficulty().getChatColor(),
                                    course.getDifficulty().getTitle())));
                }
                case FINISH -> {
                    firstLine = textLine("§a§l > ZIEL <");
                    secondLine = textLine("§7Parkour: §e{}", new TextLineModifiers().args(course.getName()));
                }
                case CHECKPOINT -> {
                    firstLine = textLine("§e§l> CHECKPOINT §6§l{} §r§e§l<", new TextLineModifiers().args(checkpoint.getIndex()));
                }
            }
        }

    }
```

**Comment by unldenis** [comment]
> I am using [ProtocolLib 5.3.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/5.3.0) on a Paper 1.19.4 server. 


Have you tried using latest ProtocolLib build?

**Comment by tgross03** [comment]
> Have you tried using latest ProtocolLib build?

I originally used the latest release but it still does not work using the last build [#735](https://ci.dmulloy2.net/job/ProtocolLib/735/).

Is it possible that a conflict with another plugin causes those kind of problems?

**Comment by unldenis** [comment]
Hi @tgross03 , 

in the meantime I receive a response in my issue, HoloEasy withversion 4.2.0 adds PacketEvents support. 

You can read more in the documentation.

**Comment by tgross03** [comment]
Hey @unldenis,

thanks for your quick response! I tried the variant with PacketEvents and the Holograms now work again
with the exception that custom Colors (`net.md_5.bungee.api`) are not shown anymore. Instead a non related
normal Color (e.g. `§8`) is shown.

Is this a problem with my method or does this variant not support this kind of colors?

My implementation:

```java
        TextComponent textComponent = new TextComponent(text);
        textComponent.setColor(color);
        return textComponent.toLegacyText();
```

**Comment by unldenis** [comment]
Since 4.2.1 colors are supported (tested in 1.20.2).

PacketEvents allows you to pass a TextComponent.
However in order not to break the api I **momentarily** [parsed ](https://github.com/unldenis/holoeasy/blob/970a9ebdcb9861f2b8f8dc989e6e5950f093d558/holoeasy-core/src/main/kotlin/org/holoeasy/packet/PacketEventsPackets.kt#L159)a string into a component.
